CREATE USER ABCPROD_31JUL IDENTIFIED BY admin
DEFAULT TABLESPACE TBFES;
GRANT DBA TO ABCPROD_31JUL;
GRANT CREATE SESSION,CREATE TABLE,CREATE SEQUENCE,
CREATE VIEW TO ABCPROD_31JUL;
GRANT EXECUTE ON DBMS_SQLHASH TO ABCPROD_31JUL;
GRANT EXECUTE ON DBMS_LOCK TO ABCPROD_31JUL;
GRANT DEBUG CONNECT SESSION TO ABCPROD_31JUL;
GRANT DEBUG ANY PROCEDURE TO ABCPROD_31JUL;
GRANT DBA TO ABCPROD_31JUL;
GRANT CREATE SESSION,CREATE TABLE,CREATE SEQUENCE,
CREATE VIEW TO ABCPROD_31JUL;
GRANT EXECUTE ON DBMS_SQLHASH TO ABCPROD_31JUL;
GRANT EXECUTE ON DBMS_LOCK TO ABCPROD_31JUL;
GRANT DEBUG CONNECT SESSION TO ABCPROD_31JUL;
GRANT DEBUG ANY PROCEDURE TO ABCPROD_31JUL;
GRANT READ,WRITE ON DIRECTORY DUMP TO ABCPROD_31JUL;
GRANT CREATE TYPE TO ABCPROD_31JUL;

impdp XYZOROD_1AUG/admin@ORCL schemas=XYZPROD_24JUL directory=DUMP dumpfile=XYZPROD_24JUL_1ST_AUGST.DMP  logfile=XYZPROD_24JUL_1ST_AUGST.DMP.log remap_schema=XYZPROD_24JUL:XYZOROD_1AUG


expdp XYZOROD_1AUG/admin@ORCL schemas=XYZOROD_1AUG directory=DUMP dumpfile=SEED_XYZ.DMP  logfile=SEED_XYZ.log
